config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cedulas

  # StaticPages
  get "home" => "static_pages#home"
  get "about" => "static_pages#about"
  get "faq" => "static_pages#faq"
  get "terms" => "static_pages#terms"
  get "privacy" => "static_pages#privacy"

  # You can have the root of your site routed with "root"
  root "static_pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cedula.rb
# frozen_string_literal: true

class Cedula < ApplicationRecord
  validates :cedula_number, uniqueness: { scope: :cedula_type, message: "Cedula number %{value} already exists" }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cedulas_controller.rb
# frozen_string_literal: true

class CedulasController < ApplicationController
  before_action :set_cedula, only: [:show, :edit, :update, :destroy]

  # GET /cedulas
  # GET /cedulas.json
  def index
    @cedulas = Cedula.paginate(page: params[:page], per_page: 20).order("id ASC")
    # @cedulas = Cedula.all
  end

  # GET /cedulas/1
  # GET /cedulas/1.json
  def show
  end

  # GET /cedulas/new
  def new
    @cedula = Cedula.new
  end

  # GET /cedulas/1/edit
  def edit
  end

  # POST /cedulas
  # POST /cedulas.json
  def create
    @cedula = Cedula.new(cedula_params)

    respond_to do |format|
      if @cedula.save
        format.html { redirect_to(@cedula, notice: "Cedula was successfully created.") }
        format.json { render(:show, status: :created, location: @cedula) }
      else
        format.html { render(:new) }
        format.json { render(json: @cedula.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /cedulas/1
  # PATCH/PUT /cedulas/1.json
  def update
    respond_to do |format|
      if @cedula.update(cedula_params)
        format.html { redirect_to(@cedula, notice: "Cedula was successfully updated.") }
        format.json { render(:show, status: :ok, location: @cedula) }
      else
        format.html { render(:edit) }
        format.json { render(json: @cedula.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /cedulas/1
  # DELETE /cedulas/1.json
  def destroy
    @cedula.destroy
    respond_to do |format|
      format.html { redirect_to(cedulas_url, notice: "Cedula was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cedula
    @cedula = Cedula.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cedula_params
    params.require(:cedula).permit(:cedula_number, :cedula_type, :name, :last_name_1, :last_name_2, :gender, :title,
      :institution, :year)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    @cedulas = Cedula.distinct.count("cedula_number")
    @titles = Cedula.distinct.count("title")
    @institutions = Cedula.distinct.count("institution")
  end

  def about
  end

  def faq
  end

  def privacy
  end

  def terms
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cedulas_helper.rb
# frozen_string_literal: true

module CedulasHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/cedulas/_form.html.erb
<%= form_with(model: cedula, local: true) do |form| %>
  <% if cedula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cedula.errors.count, "error") %> prohibited this cedula from being saved:</h2>

      <ul>
      <% cedula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cedula_number %>
    <%= form.number_field :cedula_number %>
  </div>

  <div class="field">
    <%= form.label :cedula_type %>
    <%= form.text_field :cedula_type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name_1 %>
    <%= form.text_field :last_name_1 %>
  </div>

  <div class="field">
    <%= form.label :last_name_2 %>
    <%= form.text_field :last_name_2 %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.check_box :gender %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cedulas/edit.html.erb
<h1>Editing Cedula</h1>

<%= render 'form', cedula: @cedula %>

<%= link_to 'Show', @cedula %> |
<%= link_to 'Back', cedulas_path %>

app/views/cedulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cedulas</h1>

<table>
  <thead>
    <tr>
      <th>Cedula number</th>
      <th>Cedula type</th>
      <th>Name</th>
      <th>Last name 1</th>
      <th>Last name 2</th>
      <th>Gender</th>
      <th>Title</th>
      <th>Institution</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cedulas.each do |cedula| %>
      <tr>
        <td><%= cedula.cedula_number %></td>
        <td><%= cedula.cedula_type %></td>
        <td><%= cedula.name %></td>
        <td><%= cedula.last_name_1 %></td>
        <td><%= cedula.last_name_2 %></td>
        <td><%= cedula.gender %></td>
        <td><%= cedula.title %></td>
        <td><%= cedula.institution %></td>
        <td><%= cedula.year %></td>
        <td><%= link_to 'Show', cedula %></td>
        <td><%= link_to 'Edit', edit_cedula_path(cedula) %></td>
        <td><%= link_to 'Destroy', cedula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cedulas %>

<br>

<%= link_to 'New Cedula', new_cedula_path %>

app/views/cedulas/new.html.erb
<h1>New Cedula</h1>

<%= render 'form', cedula: @cedula %>

<%= link_to 'Back', cedulas_path %>

app/views/cedulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula number:</strong>
  <%= @cedula.cedula_number %>
</p>

<p>
  <strong>Cedula type:</strong>
  <%= @cedula.cedula_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cedula.name %>
</p>

<p>
  <strong>Last name 1:</strong>
  <%= @cedula.last_name_1 %>
</p>

<p>
  <strong>Last name 2:</strong>
  <%= @cedula.last_name_2 %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @cedula.gender %>
</p>

<p>
  <strong>Title:</strong>
  <%= @cedula.title %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @cedula.institution %>
</p>

<p>
  <strong>Year:</strong>
  <%= @cedula.year %>
</p>

<%= link_to 'Edit', edit_cedula_path(@cedula) %> |
<%= link_to 'Back', cedulas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CedulaScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/faq.html.erb
<h1>StaticPages#faq</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Cedulas Profesionales</h1>
<table>
<tr>
    <td><strong>Cedulas</strong></td>
    <td><%= @cedulas %></td>
</tr>
<tr>
    <td><strong>Titles</strong></td>
    <td><%= @titles %></td>
</tr>
<tr>
    <td><strong>Institutions</strong></td>
    <td><%= @institutions %></td>
</tr>
</table>

<%= link_to 'See all cedulas', cedulas_path %>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/terms.html.erb
<h1>StaticPages#terms</h1>
<p>Find me in app/views/static_pages/terms.html.erb</p>